from typing import List, Dict
import json
from datetime import datetime
from enum import Enum
from pydantic import BaseModel, Field, ValidationError, model_validator


class Rank(Enum):
    """Enum class for crew rank"""
    cadet = "cadet"
    officer = "officer"
    lieutenant = "lieutenant"
    captain = "captain"
    commander = "commander"


class CrewMember(BaseModel):
    """Class to initialize crew members"""
    member_id: str = Field(min_length=3, max_length=10)
    name: str = Field(min_length=2, max_length=50)
    rank: Rank
    age: int = Field(ge=18, le=80)
    specialization: str = Field(min_length=3, max_length=30)
    years_experience: int = Field(ge=0, le=50)
    is_active: bool = True


class SpaceMission(BaseModel):
    """Class to initialize the mission details"""
    mission_id: str = Field(min_length=5, max_length=15)
    mission_name: str = Field(min_length=3, max_length=100)
    destination: str = Field(min_length=3, max_length=50)
    launch_date: datetime
    duration_days: int = Field(ge=1, le=3650)
    crew: List[CrewMember]
    mission_status: str = "planned"
    budget_millions: float = Field(ge=1.0, le=10000.0)

    @model_validator(mode='after')
    def validate_mission(self):
        """Validate the mission details"""
        if not self.mission_id.startswith("M"):
            raise ValueError("Mission ID must start with 'M'")
        if not self.is_captain_in_crew():
            raise ValueError("Must have at least one" +
                             "Commander or Captain")
        if self.duration_days > 365 and\
           self.experienced_crew_percent(5) < 50:
            raise ValueError("Long missions (> 365 days) need" +
                             " 50% experienced crew (5+ years)")
        if not self.is_all_crew_active():
            raise ValueError("All crew members must be active")
        return self

    def is_captain_in_crew(self) -> bool:
        """Return if caption/ commander is there in the selected crew"""
        for crew in self.crew:
            if crew.rank.value == "captain" or\
               crew.rank.value == "commander":
                return True
        return False

    def is_all_crew_active(self) -> bool:
        """Check if all crew member is active or not"""
        for crew in self.crew:
            if not crew.is_active:
                return False
        return True

    def experienced_crew_percent(self, years: int) -> float:
        """Calculate the percentage of crew members has more than
           required years of experience"""
        num_experience_crew = 0
        for crew in self.crew:
            if crew.years_experience >= years:
                num_experience_crew += 1
        return (num_experience_crew * 100 / len(self.crew))


def show_mission_details(id: str, mission: str, destination: str,
                         duration: int, budget: int | float,
                         crews: List[CrewMember]) -> None:
    """Show mission details in required formatting"""
    print(f"Mission: {mission}")
    print(f"ID: {id}")
    print(f"Destination: {destination}")
    print(f"Duration: {duration} days")
    print(f"Budget: ${budget}M")
    print(f"Crew size: {len(crews)}")
    print("Crew members:")
    for crew in crews:
        print(f"- {crew.name} ({crew.rank.value})" +
              f" - {crew.specialization}")


def load_json_data(file_name) -> Dict:
    """Load json data from the example generated by data generator"""
    with open(file_name, "r") as file:
        data = json.load(file)
    return data


def main():
    all_data = load_json_data("space_missions.json")
    print("Space Mission Crew Validation")
    for data in all_data:
        try:
            obs = SpaceMission(**data)
            print("\n======================================")
            print("Valid mission created:")
            show_mission_details(obs.mission_id, obs.mission_name,
                                 obs.destination, obs.duration_days,
                                 obs.budget_millions, obs.crew)
        except ValidationError as e:
            print("\n======================================")
            print("Expected validation error:")
            print(e)


if __name__ == "__main__":
    main()
