from datetime import datetime
from typing import Optional, Dict
import json
from enum import Enum
from pydantic import BaseModel, ValidationError, Field, model_validator


class ContactType(Enum):
    """Enum class for observation types"""
    radio = "radio"
    visual = "visual"
    physical = "physical"
    telepathic = "telepathic"


class AlienContact(BaseModel):
    """Class to initialize Alien observation report"""
    contact_id: str = Field(min_length=5, max_length=15)
    timestamp: datetime
    location: str = Field(min_length=3, max_length=100)
    contact_type: ContactType
    signal_strength: float = Field(ge=0.0, le=10.0)
    duration_minutes: int = Field(ge=1, le=1440)
    witness_count: int = Field(ge=1, le=100)
    message_received: Optional[str] = Field(default=None, max_length=500)
    is_verified: bool = False

    @model_validator(mode='after')
    def validate_observation(self):
        """Validate if the observation are valid or not"""
        if not self.contact_id.startswith("AC"):
            raise ValueError("Contact ID must start with 'AC'")
        if self.contact_type.value == "physical" and\
           not self.is_verified:
            raise ValueError("Physical contact much be verified")
        if self.contact_type.value == "telepathic" and\
           self.witness_count < 3:
            raise ValueError("Telepathic contact much be witnessed by"
                             " at least 3 people")
        if self.signal_strength > 7.0 and\
           not self.message_received:
            raise ValueError("Strong signals (>7.0) require a message")
        return self


def show_station_details(id: str, com_type: str, location: str,
                         signal: float, duration: int,
                         witnesses: int, msg: str) -> None:
    """Show alien observation in required formatting"""
    print(f"ID: {id}")
    print(f"Type: {com_type}")
    print(f"Location: {location}")
    print(f"Signal: {signal}/10")
    print(f"Duration: {duration} minutes")
    print(f"Witnesses: {witnesses}")
    if msg is not None:
        print(f"Message: {msg}")


def load_json_data(file_name) -> Dict:
    """Load json data from the example generated by data generator"""
    with open(file_name, "r") as file:
        data = json.load(file)
    return data


def main():
    all_data = load_json_data("alien_contacts.json")
    print("Alien Contact Log Validation")
    for data in all_data:
        try:
            obs = AlienContact(**data)
            msg = None
            if obs.signal_strength > 7:
                msg = obs.message_received
            print("\n======================================")
            print("Valid contact report:")
            show_station_details(obs.contact_id, obs.contact_type.value,
                                 obs.location, obs.signal_strength,
                                 obs.duration_minutes, obs.witness_count,
                                 msg)
        except ValidationError as e:
            print("\n======================================")
            print(e.errors()[0].get('msg'))


if __name__ == "__main__":
    main()
